#!/bin/sh

here="$(realpath -- "$(dirname -- $0)")"
export PATH="$here":"$PATH"

printf %s "$(id -un)" > /proc/self/comm

while true; do
  busybody-watch-git
  busybody-tasks
  busybody-micronap
done
